// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { context } from "$live/live.ts";
import { DecoManifest } from "$live/types.ts";
import * as $0 from "./routes/[...catchall].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/[...catchall].tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/inspect-vscode.ts";
import * as $$0 from "./islands/AddToCartButton.tsx";
import * as $$1 from "./islands/Alert.tsx";
import * as $$2 from "./islands/HeaderButton.tsx";
import * as $$3 from "./islands/HeaderModals.tsx";
import * as $$4 from "./islands/LiveControls.tsx";
import * as $$5 from "./islands/SearchControls.tsx";
import * as $$6 from "./islands/Slick.tsx";
import * as $$$0 from "./sections/Advocate.tsx";
import * as $$$1 from "./sections/Carousel.tsx";
import * as $$$2 from "./sections/DesignSystem.story.tsx";
import * as $$$3 from "./sections/Features.tsx";
import * as $$$4 from "./sections/Footer.tsx";
import * as $$$5 from "./sections/Head.tsx";
import * as $$$6 from "./sections/Header.tsx";
import * as $$$7 from "./sections/Highlights.tsx";
import * as $$$8 from "./sections/JoinUs.tsx";
import * as $$$9 from "./sections/ProductDetails.tsx";
import * as $$$10 from "./sections/ProductGallery.tsx";
import * as $$$11 from "./sections/ProductShelf.tsx";
import * as $$$12 from "./sections/SearchControls.tsx";
import * as $$$13 from "./sections/Seo.tsx";
import * as $$$14 from "./sections/SeoPDP.tsx";
import * as $$$15 from "./sections/SeoPLP.tsx";
import * as $$$16 from "./sections/vtexconfig.global.tsx";
import * as $$$17 from "$live/sections/Head.tsx";
import * as $$$$0 from "./functions/occProductDetailsPage.ts";
import * as $$$$1 from "./functions/shopifyProductDetailsPage.ts";
import * as $$$$2 from "./functions/shopifyProductList.ts";
import * as $$$$3 from "./functions/shopifyProductListingPage.ts";
import * as $$$$4 from "./functions/vtexLegacyProductDetailsPage.ts";
import * as $$$$5 from "./functions/vtexLegacyProductList.ts";
import * as $$$$6 from "./functions/vtexLegacyProductListingPage.ts";
import * as $$$$7 from "./functions/vtexProductDetailsPage.ts";
import * as $$$$8 from "./functions/vtexProductList.ts";
import * as $$$$9 from "./functions/vtexProductListingPage.ts";
import * as $$$$10 from "$live/functions/EffectSelectPage.ts";
import * as $$$$11 from "$live/functions/MatchDate.ts";
import * as $$$$12 from "$live/functions/MatchEnvironment.ts";
import * as $$$$13 from "$live/functions/MatchRandom.ts";
import * as $$$$14 from "$live/functions/MatchSite.ts";
import * as $$$$15 from "$live/functions/MatchUserAgent.ts";

const manifest: DecoManifest = {
  routes: {
    "./routes/[...catchall].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/[...catchall].tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/inspect-vscode.ts": $5,
  },
  islands: {
    "./islands/AddToCartButton.tsx": $$0,
    "./islands/Alert.tsx": $$1,
    "./islands/HeaderButton.tsx": $$2,
    "./islands/HeaderModals.tsx": $$3,
    "./islands/LiveControls.tsx": $$4,
    "./islands/SearchControls.tsx": $$5,
    "./islands/Slick.tsx": $$6,
  },
  sections: {
    "./sections/Advocate.tsx": $$$0,
    "./sections/Carousel.tsx": $$$1,
    "./sections/DesignSystem.story.tsx": $$$2,
    "./sections/Features.tsx": $$$3,
    "./sections/Footer.tsx": $$$4,
    "./sections/Head.tsx": $$$5,
    "./sections/Header.tsx": $$$6,
    "./sections/Highlights.tsx": $$$7,
    "./sections/JoinUs.tsx": $$$8,
    "./sections/ProductDetails.tsx": $$$9,
    "./sections/ProductGallery.tsx": $$$10,
    "./sections/ProductShelf.tsx": $$$11,
    "./sections/SearchControls.tsx": $$$12,
    "./sections/Seo.tsx": $$$13,
    "./sections/SeoPDP.tsx": $$$14,
    "./sections/SeoPLP.tsx": $$$15,
    "./sections/vtexconfig.global.tsx": $$$16,
    "$live/sections/Head.tsx": $$$17,
  },
  functions: {
    "./functions/occProductDetailsPage.ts": $$$$0,
    "./functions/shopifyProductDetailsPage.ts": $$$$1,
    "./functions/shopifyProductList.ts": $$$$2,
    "./functions/shopifyProductListingPage.ts": $$$$3,
    "./functions/vtexLegacyProductDetailsPage.ts": $$$$4,
    "./functions/vtexLegacyProductList.ts": $$$$5,
    "./functions/vtexLegacyProductListingPage.ts": $$$$6,
    "./functions/vtexProductDetailsPage.ts": $$$$7,
    "./functions/vtexProductList.ts": $$$$8,
    "./functions/vtexProductListingPage.ts": $$$$9,
    "$live/functions/EffectSelectPage.ts": $$$$10,
    "$live/functions/MatchDate.ts": $$$$11,
    "$live/functions/MatchEnvironment.ts": $$$$12,
    "$live/functions/MatchRandom.ts": $$$$13,
    "$live/functions/MatchSite.ts": $$$$14,
    "$live/functions/MatchUserAgent.ts": $$$$15,
  },
  schemas: {
    "./sections/Advocate.tsx": {
      "inputSchema": {
        "title": " Advocate",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "title": "Title",
            "description": "The title of this section",
          },
          "content": {
            "type": "string",
            "title": "Content",
            "description": "The content of this section",
          },
          "cta": {
            "type": "string",
            "title": "Cards",
            "description": "The configuration of the cards of this section",
          },
        },
        "required": [
          "title",
          "content",
          "cta",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Carousel.tsx": {
      "inputSchema": {
        "title": " Carousel",
        "type": "object",
        "properties": {
          "images": {
            "type": "array",
            "items": {
              "title": "Image",
              "type": "object",
              "properties": {
                "desktop": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Desktop",
                  "description": "desktop otimized image",
                },
                "mobile": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Mobile",
                  "description": "mobile otimized image",
                },
                "href": {
                  "type": "string",
                  "title": "Href",
                  "description":
                    "when user clicks on the image, go to this link",
                },
                "alt": {
                  "type": "string",
                  "title": "Alt",
                  "description": "Image's alt text",
                },
                "title": {
                  "type": "string",
                  "title": "Title",
                  "description": "slide title",
                },
                "description": {
                  "type": "string",
                  "title": "Description",
                  "description": "slide description",
                },
                "cta": {
                  "type": "string",
                  "title": "Call to action",
                },
              },
              "required": [
                "desktop",
                "mobile",
                "href",
                "alt",
                "title",
                "description",
                "cta",
              ],
            },
            "title": "Images",
            "description": "List of images to display in the carousel",
          },
          "preload": {
            "type": [
              "boolean",
              "null",
            ],
            "title": "Preload",
            "description":
              "Check this option when this banner is the biggest image on the screen for image optimizations",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "./sections/DesignSystem.story.tsx": {
      "inputSchema": null,
      "outputSchema": null,
    },
    "./sections/Features.tsx": {
      "inputSchema": {
        "title": " Features",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "title": "Title",
          },
          "description": {
            "type": "string",
            "title": "Description",
          },
          "features": {
            "type": "array",
            "items": {
              "title": "Feature",
              "type": "object",
              "properties": {
                "icon": {
                  "type": "string",
                  "anyOf": [
                    {
                      "type": "string",
                      "const": "Circle",
                    },
                    {
                      "type": "string",
                      "const": "ChevronLeft",
                    },
                    {
                      "type": "string",
                      "const": "ChevronRight",
                    },
                    {
                      "type": "string",
                      "const": "QuestionMarkCircle",
                    },
                    {
                      "type": "string",
                      "const": "User",
                    },
                    {
                      "type": "string",
                      "const": "ShoppingCart",
                    },
                    {
                      "type": "string",
                      "const": "Bars3",
                    },
                    {
                      "type": "string",
                      "const": "Heart",
                    },
                    {
                      "type": "string",
                      "const": "MagnifyingGlass",
                    },
                    {
                      "type": "string",
                      "const": "XMark",
                    },
                    {
                      "type": "string",
                      "const": "Elo",
                    },
                    {
                      "type": "string",
                      "const": "Mastercard",
                    },
                    {
                      "type": "string",
                      "const": "Visa",
                    },
                    {
                      "type": "string",
                      "const": "Pix",
                    },
                    {
                      "type": "string",
                      "const": "Logo",
                    },
                    {
                      "type": "string",
                      "const": "Facebook",
                    },
                    {
                      "type": "string",
                      "const": "Instagram",
                    },
                    {
                      "type": "string",
                      "const": "Tiktok",
                    },
                    {
                      "type": "string",
                      "const": "Truck",
                    },
                    {
                      "type": "string",
                      "const": "Discount",
                    },
                    {
                      "type": "string",
                      "const": "Return",
                    },
                    {
                      "type": "string",
                      "const": "CreditCard",
                    },
                    {
                      "type": "string",
                      "const": "Deco",
                    },
                    {
                      "type": "string",
                      "const": "Discord",
                    },
                    {
                      "type": "string",
                      "const": "FilterList",
                    },
                    {
                      "type": "string",
                      "const": "ChevronUp",
                    },
                    {
                      "type": "string",
                      "const": "ProvenResults",
                    },
                    {
                      "type": "string",
                      "const": "IngredientsSafety",
                    },
                    {
                      "type": "string",
                      "const": "SustainablyDesigned",
                    },
                    {
                      "type": "string",
                      "const": "Advocacy",
                    },
                  ],
                  "title": "Icon",
                  "description": "Image src",
                },
                "title": {
                  "type": "string",
                  "title": "Title",
                  "description": "Title",
                },
                "description": {
                  "type": "string",
                  "title": "Description",
                  "description": "Description and Image alt text",
                },
              },
              "required": [
                "icon",
                "title",
                "description",
              ],
            },
            "title": "Features",
          },
        },
        "required": [
          "title",
          "description",
          "features",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Footer.tsx": {
      "inputSchema": {
        "title": " Footer",
        "type": "object",
        "properties": {
          "newsletter": {
            "title": "Newsletter",
            "type": "object",
            "properties": {
              "title": {
                "type": "string",
                "title": "Title",
              },
              "description": {
                "type": "string",
                "title": "Description",
              },
            },
            "required": [
              "title",
              "description",
            ],
          },
          "finalText": {
            "type": "string",
            "title": "Final Text",
          },
          "sections": {
            "type": "array",
            "items": {
              "title": "Section",
              "type": "object",
              "properties": {
                "label": {
                  "type": "string",
                  "title": "Label",
                },
                "children": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "anyOf": [
                      {
                        "title": "StringItem",
                        "type": "object",
                        "properties": {
                          "label": {
                            "type": "string",
                            "title": "Label",
                          },
                          "href": {
                            "type": "string",
                            "title": "Href",
                          },
                        },
                        "required": [
                          "label",
                          "href",
                        ],
                      },
                      {
                        "title": "IconItem",
                        "type": "object",
                        "properties": {
                          "icon": {
                            "type": "string",
                            "anyOf": [
                              {
                                "type": "string",
                                "const": "Circle",
                              },
                              {
                                "type": "string",
                                "const": "ChevronLeft",
                              },
                              {
                                "type": "string",
                                "const": "ChevronRight",
                              },
                              {
                                "type": "string",
                                "const": "QuestionMarkCircle",
                              },
                              {
                                "type": "string",
                                "const": "User",
                              },
                              {
                                "type": "string",
                                "const": "ShoppingCart",
                              },
                              {
                                "type": "string",
                                "const": "Bars3",
                              },
                              {
                                "type": "string",
                                "const": "Heart",
                              },
                              {
                                "type": "string",
                                "const": "MagnifyingGlass",
                              },
                              {
                                "type": "string",
                                "const": "XMark",
                              },
                              {
                                "type": "string",
                                "const": "Elo",
                              },
                              {
                                "type": "string",
                                "const": "Mastercard",
                              },
                              {
                                "type": "string",
                                "const": "Visa",
                              },
                              {
                                "type": "string",
                                "const": "Pix",
                              },
                              {
                                "type": "string",
                                "const": "Logo",
                              },
                              {
                                "type": "string",
                                "const": "Facebook",
                              },
                              {
                                "type": "string",
                                "const": "Instagram",
                              },
                              {
                                "type": "string",
                                "const": "Tiktok",
                              },
                              {
                                "type": "string",
                                "const": "Truck",
                              },
                              {
                                "type": "string",
                                "const": "Discount",
                              },
                              {
                                "type": "string",
                                "const": "Return",
                              },
                              {
                                "type": "string",
                                "const": "CreditCard",
                              },
                              {
                                "type": "string",
                                "const": "Deco",
                              },
                              {
                                "type": "string",
                                "const": "Discord",
                              },
                              {
                                "type": "string",
                                "const": "FilterList",
                              },
                              {
                                "type": "string",
                                "const": "ChevronUp",
                              },
                              {
                                "type": "string",
                                "const": "ProvenResults",
                              },
                              {
                                "type": "string",
                                "const": "IngredientsSafety",
                              },
                              {
                                "type": "string",
                                "const": "SustainablyDesigned",
                              },
                              {
                                "type": "string",
                                "const": "Advocacy",
                              },
                            ],
                            "title": "Icon",
                          },
                        },
                        "required": [
                          "icon",
                        ],
                      },
                    ],
                    "title": "Item",
                  },
                  "title": "Children",
                },
              },
              "required": [
                "label",
                "children",
              ],
            },
            "title": "Sections",
          },
        },
        "required": [
          "newsletter",
          "finalText",
          "sections",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Head.tsx": {
      "inputSchema": null,
      "outputSchema": null,
    },
    "./sections/Header.tsx": {
      "inputSchema": {
        "title": " Header",
        "type": "object",
        "properties": {
          "alerts": {
            "type": "array",
            "items": {
              "title": "EditableAlert",
              "type": "object",
              "properties": {
                "text": {
                  "type": "string",
                  "title": "Text",
                  "description": "The text to display in the alert",
                },
                "style": {
                  "type": "string",
                  "anyOf": [
                    {
                      "type": "string",
                      "const": "dark",
                    },
                    {
                      "type": "string",
                      "const": "decorative-one",
                    },
                    {
                      "type": "string",
                      "const": "decorative-two",
                    },
                    {
                      "type": "string",
                      "const": "decorative-three",
                    },
                    {
                      "type": "string",
                      "const": "decorative-four",
                    },
                    {
                      "type": "string",
                      "const": "decorative-five",
                    },
                  ],
                  "title": "Style",
                  "description": "The style to use for this alert",
                },
                "cta": {
                  "type": [
                    "string",
                    "null",
                  ],
                  "title": "Action text",
                  "description":
                    "The text to display in the alert call to action",
                },
              },
              "required": [
                "text",
                "style",
              ],
            },
            "title": "Alerts",
          },
          "searchbar": {
            "title": "Search Bar",
            "type": "object",
            "properties": {
              "placeholder": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Placeholder",
                "description": "Search bar default placeholder message",
                "default": "What are you looking for?",
              },
              "action": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Page path",
                "description":
                  "When user clicks on the search button, navigate it to",
                "default": "/s",
              },
              "name": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Term name",
                "description":
                  "Querystring param used when navigating the user",
                "default": "q",
              },
              "query": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Query",
              },
            },
            "required": [],
          },
          "navItems": {
            "type": "array",
            "items": {
              "title": "Item",
              "type": "object",
              "properties": {
                "href": {
                  "type": "string",
                  "title": "Href",
                },
                "label": {
                  "type": "string",
                  "title": "Label",
                },
                "children": {
                  "type": "array",
                  "items": {
                    "title": "NavLink",
                    "type": "object",
                    "properties": {
                      "label": {
                        "type": "string",
                        "title": "Label",
                      },
                      "href": {
                        "type": "string",
                        "title": "Href",
                        "default": "/",
                      },
                    },
                    "required": [
                      "label",
                      "href",
                    ],
                  },
                  "title": "Children",
                },
                "featured": {
                  "type": "array",
                  "items": {
                    "title": "NavLink",
                    "type": "object",
                    "properties": {
                      "label": {
                        "type": "string",
                        "title": "Label",
                      },
                      "href": {
                        "type": "string",
                        "title": "Href",
                        "default": "/",
                      },
                    },
                    "required": [
                      "label",
                      "href",
                    ],
                  },
                  "title": "Featured",
                },
                "image": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Image",
                  "description": "image to be shown inside the megamenu",
                },
              },
              "required": [
                "href",
                "label",
              ],
            },
            "title": "Navigation items",
            "description":
              "Navigation items used both on mobile and desktop menus",
          },
          "products": {
            "$id": "9091c349b893f5d60af9017849735ee9f21e2ba0",
            "format": "live-function",
            "type": "string",
            "title": "Product suggestions",
            "description": "Product suggestions displayed on search",
          },
        },
        "required": [
          "alerts",
          "navItems",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Highlights.tsx": {
      "inputSchema": {
        "title": " Highlights",
        "type": "object",
        "properties": {
          "highlights": {
            "type": "array",
            "items": {
              "title": "Highlight",
              "type": "object",
              "properties": {
                "src": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Src",
                },
                "alt": {
                  "type": "string",
                  "title": "Alt",
                },
                "href": {
                  "type": "string",
                  "title": "Href",
                },
                "label": {
                  "type": "string",
                  "title": "Label",
                },
              },
              "required": [
                "src",
                "alt",
                "href",
                "label",
              ],
            },
            "title": "Highlights",
          },
          "title": {
            "type": "string",
            "title": "Title",
          },
        },
        "required": [
          "title",
        ],
      },
      "outputSchema": null,
    },
    "./sections/JoinUs.tsx": {
      "inputSchema": {
        "title": " Join Us",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "title": "Title",
            "description": "The title of this section",
          },
          "content": {
            "type": "string",
            "title": "Content",
            "description": "The content of this section",
          },
          "cards": {
            "type": "array",
            "items": {
              "title": "Card",
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "title": "Title",
                },
                "description": {
                  "type": "string",
                  "title": "Description",
                },
                "cta": {
                  "type": "string",
                  "title": "Cta",
                },
                "image": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Image",
                },
              },
              "required": [
                "title",
                "description",
                "cta",
                "image",
              ],
            },
            "title": "Cards",
            "description": "The configuration of the cards of this section",
          },
        },
        "required": [
          "title",
          "content",
          "cards",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductDetails.tsx": {
      "inputSchema": {
        "title": " Product Details",
        "type": "object",
        "properties": {
          "page": {
            "$id": "906909daeb7d99a3eb0e05ff52e42d7b9c5b298a",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductGallery.tsx": {
      "inputSchema": {
        "title": " Product Gallery",
        "type": "object",
        "properties": {
          "page": {
            "$id": "4246b2b7d22c6a301356a5b3c9c5d48523654a0f",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/ProductShelf.tsx": {
      "inputSchema": {
        "title": " Product Shelf",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "title": "Title",
          },
          "products": {
            "$id": "9091c349b893f5d60af9017849735ee9f21e2ba0",
            "format": "live-function",
            "type": "string",
            "title": "Products",
          },
        },
        "required": [
          "title",
          "products",
        ],
      },
      "outputSchema": null,
    },
    "./sections/SearchControls.tsx": {
      "inputSchema": {
        "title": " Search Controls",
        "type": "object",
        "properties": {
          "page": {
            "$id": "4246b2b7d22c6a301356a5b3c9c5d48523654a0f",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Seo.tsx": {
      "inputSchema": {
        "title": " Seo",
        "type": "object",
        "properties": {
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Title",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Description",
          },
          "url": {
            "type": [
              "string",
              "null",
            ],
            "title": "Url",
          },
          "imageUrl": {
            "type": [
              "string",
              "null",
            ],
            "title": "Image Url",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "./sections/SeoPDP.tsx": {
      "inputSchema": {
        "title": " Seo P D P",
        "type": "object",
        "properties": {
          "page": {
            "$id": "906909daeb7d99a3eb0e05ff52e42d7b9c5b298a",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
          "titleTemplate": {
            "type": "string",
            "title": "Title template",
            "description":
              "add a %s whenever you want it to be replaced with the product name",
            "default": "%s | Fashion Store",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Meta tag description",
            "description":
              "If not set, the product description will be used instead",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [
          "page",
          "titleTemplate",
        ],
      },
      "outputSchema": null,
    },
    "./sections/SeoPLP.tsx": {
      "inputSchema": {
        "title": " Seo P L P",
        "type": "object",
        "properties": {
          "page": {
            "$id": "4246b2b7d22c6a301356a5b3c9c5d48523654a0f",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Title",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Description",
          },
          "url": {
            "type": [
              "string",
              "null",
            ],
            "title": "Url",
          },
          "imageUrl": {
            "type": [
              "string",
              "null",
            ],
            "title": "Image Url",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "./sections/vtexconfig.global.tsx": {
      "inputSchema": {
        "title": "Vtexconfig.global",
        "type": "object",
        "properties": {
          "account": {
            "type": "string",
            "title": "Account",
            "description":
              "VTEX Account name. For more info, read here: https://help.vtex.com/en/tutorial/o-que-e-account-name--i0mIGLcg3QyEy8OCicEoC.",
          },
          "salesChannel": {
            "type": "string",
            "title": "Sales Channel",
            "description":
              "VTEX sales channel. This will be the default sales channel your site. For more info, read here: https://help.vtex.com/tutorial/how-trade-policies-work--6Xef8PZiFm40kg2STrMkMV",
          },
          "locale": {
            "type": "string",
            "title": "Locale",
            "description": "Locale used for VTEX Intelligent Search client.",
          },
          "priceCurrency": {
            "type": "string",
            "title": "Price Currency",
            "description": "Default price currency.",
            "default": "USD",
          },
        },
        "required": [
          "account",
          "salesChannel",
          "locale",
          "priceCurrency",
        ],
      },
      "outputSchema": null,
    },
    "./functions/occProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Occ Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "906909daeb7d99a3eb0e05ff52e42d7b9c5b298a",
          },
        },
        "additionalProperties": true,
      },
    },
    "./functions/shopifyProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Shopify Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "906909daeb7d99a3eb0e05ff52e42d7b9c5b298a",
          },
        },
        "additionalProperties": true,
      },
    },
    "./functions/shopifyProductList.ts": {
      "inputSchema": {
        "title": "Shopify Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "search term to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "9091c349b893f5d60af9017849735ee9f21e2ba0",
          },
        },
        "additionalProperties": true,
      },
    },
    "./functions/shopifyProductListingPage.ts": {
      "inputSchema": {
        "title": "Shopify Product Listing Page",
        "type": "object",
        "properties": {
          "query": {
            "type": [
              "string",
              "null",
            ],
            "title": "Query",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "4246b2b7d22c6a301356a5b3c9c5d48523654a0f",
          },
        },
        "additionalProperties": true,
      },
    },
    "./functions/vtexLegacyProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Vtex Legacy Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "906909daeb7d99a3eb0e05ff52e42d7b9c5b298a",
          },
        },
        "additionalProperties": true,
      },
    },
    "./functions/vtexLegacyProductList.ts": {
      "inputSchema": {
        "title": "Vtex Legacy Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "query to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
          "sort": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "",
              },
              {
                "type": "string",
                "const": "price:desc",
              },
              {
                "type": "string",
                "const": "price:asc",
              },
              {
                "type": "string",
                "const": "orders:desc",
              },
              {
                "type": "string",
                "const": "name:desc",
              },
              {
                "type": "string",
                "const": "name:asc",
              },
              {
                "type": "string",
                "const": "release:desc",
              },
              {
                "type": "string",
                "const": "discount:desc",
              },
            ],
            "title": "Sort",
            "description": "search sort parameter",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "9091c349b893f5d60af9017849735ee9f21e2ba0",
          },
        },
        "additionalProperties": true,
      },
    },
    "./functions/vtexLegacyProductListingPage.ts": {
      "inputSchema": {
        "title": "Vtex Legacy Product Listing Page",
        "type": "object",
        "properties": {
          "term": {
            "type": [
              "string",
              "null",
            ],
            "title": "Term",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
          "ft": {
            "type": [
              "string",
              "null",
            ],
            "title": "Ft",
            "description": "FullText term",
          },
          "fq": {
            "type": [
              "string",
              "null",
            ],
            "title": "Fq",
          },
          "map": {
            "type": [
              "string",
              "null",
            ],
            "title": "Map",
            "description": "map param",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "4246b2b7d22c6a301356a5b3c9c5d48523654a0f",
          },
        },
        "additionalProperties": true,
      },
    },
    "./functions/vtexProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Vtex Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "906909daeb7d99a3eb0e05ff52e42d7b9c5b298a",
          },
        },
        "additionalProperties": true,
      },
    },
    "./functions/vtexProductList.ts": {
      "inputSchema": {
        "title": "Vtex Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "query to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
          "sort": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "",
              },
              {
                "type": "string",
                "const": "price:desc",
              },
              {
                "type": "string",
                "const": "price:asc",
              },
              {
                "type": "string",
                "const": "orders:desc",
              },
              {
                "type": "string",
                "const": "name:desc",
              },
              {
                "type": "string",
                "const": "name:asc",
              },
              {
                "type": "string",
                "const": "release:desc",
              },
              {
                "type": "string",
                "const": "discount:desc",
              },
            ],
            "title": "Sort",
            "description": "search sort parameter",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "9091c349b893f5d60af9017849735ee9f21e2ba0",
          },
        },
        "additionalProperties": true,
      },
    },
    "./functions/vtexProductListingPage.ts": {
      "inputSchema": {
        "title": "Vtex Product Listing Page",
        "type": "object",
        "properties": {
          "query": {
            "type": [
              "string",
              "null",
            ],
            "title": "Query",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "4246b2b7d22c6a301356a5b3c9c5d48523654a0f",
          },
        },
        "additionalProperties": true,
      },
    },
    "$live/sections/Head.tsx": {
      "inputSchema": {
        "title": " Head",
        "type": "object",
        "properties": {
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Title",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Description",
          },
          "url": {
            "type": [
              "string",
              "null",
            ],
            "title": "Url",
          },
          "imageUrl": {
            "type": [
              "string",
              "null",
            ],
            "title": "Image Url",
          },
          "faviconUrl": {
            "type": [
              "string",
              "null",
            ],
            "title": "Favicon Url",
          },
          "styleUrls": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Style Urls",
          },
          "inlineStyles": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Inline Styles",
          },
          "scriptUrls": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Script Urls",
          },
          "inlineScripts": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Inline Scripts",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "$live/functions/EffectSelectPage.ts": {
      "inputSchema": {
        "title": " Effect Select Page",
        "type": "object",
        "properties": {
          "pageIds": {
            "type": "array",
            "items": {
              "type": "number",
            },
            "title": "Page Ids",
          },
        },
        "required": [
          "pageIds",
        ],
      },
      "outputSchema": null,
    },
    "$live/functions/MatchDate.ts": {
      "inputSchema": {
        "title": " Match Date",
        "type": "object",
        "properties": {
          "start": {
            "type": [
              "string",
              "null",
            ],
            "title": "Start",
            "format": "date-time",
          },
          "end": {
            "type": [
              "string",
              "null",
            ],
            "title": "End",
            "format": "date-time",
          },
          "session": {
            "type": "boolean",
            "title": "Session",
          },
        },
        "required": [
          "session",
        ],
      },
      "outputSchema": null,
    },
    "$live/functions/MatchEnvironment.ts": {
      "inputSchema": {
        "title": " Match Environment",
        "type": "object",
        "properties": {
          "environment": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "production",
              },
              {
                "type": "string",
                "const": "development",
              },
            ],
            "title": "Environment",
          },
        },
        "required": [
          "environment",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "c995d72dc372b1b50bf9f70943e37fc94e1ccac9",
          },
        },
        "additionalProperties": true,
      },
    },
    "$live/functions/MatchRandom.ts": {
      "inputSchema": {
        "title": " Match Random",
        "type": "object",
        "properties": {
          "traffic": {
            "type": "number",
            "title": "Traffic",
          },
          "session": {
            "type": "boolean",
            "title": "Session",
          },
        },
        "required": [
          "traffic",
          "session",
        ],
      },
      "outputSchema": null,
    },
    "$live/functions/MatchSite.ts": {
      "inputSchema": {
        "title": " Match Site",
        "type": "object",
        "properties": {
          "siteId": {
            "type": "number",
            "title": "Site Id",
          },
        },
        "required": [
          "siteId",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "c995d72dc372b1b50bf9f70943e37fc94e1ccac9",
          },
        },
        "additionalProperties": true,
      },
    },
    "$live/functions/MatchUserAgent.ts": {
      "inputSchema": {
        "title": " Match User Agent",
        "type": "object",
        "properties": {
          "includes": {
            "type": [
              "string",
              "null",
            ],
            "title": "Includes",
          },
          "match": {
            "type": [
              "string",
              "null",
            ],
            "title": "Match",
          },
        },
        "required": [],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "c995d72dc372b1b50bf9f70943e37fc94e1ccac9",
          },
        },
        "additionalProperties": true,
      },
    },
  },
  baseUrl: import.meta.url,
  config,
};

// live — this exposes the manifest so the live server can render components dynamically
context.manifest = manifest;

export default manifest;
